- include_tasks: ol-7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == '7'

- include_tasks: centos-7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: debian.yml
  when: ansible_distribution == 'Debian'

- name: Ensure slurmctld logrotate config is present on controllers
  become: true
  template:
    src: slurmctld-logrotate
    dest: /etc/logrotate.d/slurmctld
    owner: root
    group: root
    mode: '0644'
  when: "'controller' in group_names"

- name: Ensure slurmdbd logrotate config is present on controllers
  become: true
  template:
    src: slurmdbd-logrotate
    dest: /etc/logrotate.d/slurmdbd
    owner: root
    group: root
    mode: '0644'
  when: "'controller' in group_names"

- name: Ensure slurmd logrotate config is present on login nodes
  become: true
  template:
    src: roles/cais-compute/templates/slurmd-logrotate
    dest: /etc/logrotate.d/slurmd
    owner: root
    group: root
    mode: '0644'
  when: "'login' in group_names"

- name: Ensure idle-job reaper logrotate config is present on controllers
  become: true
  template:
    src: reaper-logrotate
    dest: /etc/logrotate.d/reaper
    owner: root
    group: root
    mode: '0644'
  when: "'controller' in group_names"